---
title: "SAE_PEMODELAN"
author: "Amirudin"
date: '2024-05-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# DATA
```{r}
library(readxl) # untuk melakukan read data berekstensi xlsx
data<-read_excel("Data Kalimantan Fix 20 Mei.xlsx", sheet = "Full")
str(data) # melihat struktur data
```

# LIBRARY 
```{r}
library(nortest)
library(tseries)
library(emdi)
library(sae)
library(saeHB)
library(dplyr)
library(regclass)
```

# EKSPLORASI DATA
## Penduga Langsung
```{r}
summary(data$tidak_sekolah) # summary statistics dari direct estimate anak tidak sekolah
var(data$tidak_sekolah)

#Uji normalitas
lillie.test(data$tidak_sekolah)
jarque.bera.test(data$tidak_sekolah)

# berdasarkan hasil uji, direct estimate berdistribusi normal

#Histogram & Box Plot
hist(data$tidak_sekolah, col = "NAVY",  border = "white",main = "", xlab = "", ylab = "Frekuensi")

boxplot(data$tidak_sekolah, col = "Maroon", horizontal = TRUE)

# RSE
data_RSE <- data %>% 
  mutate(qual = ifelse(rse > 25, 1, 0)) # merecode direct estimate dengan rse > 25 persen 

# RSE di atas 25 persen
sum(ifelse(data_RSE$rse> 25, 1, 0))
```

## Auxiliary Variables
```{r}

# PODES
## Jarak Sekolah Terdekat dengan Desa yang Tidak Memiliki Sekolah
cor.test(data$tidak_sekolah, data$jarak_sd, method = "pearson")
cor.test(data$tidak_sekolah, data$jarak_mi, method = "pearson")
cor.test(data$tidak_sekolah, data$jarak_sd_sdrjt, method = "pearson")
cor.test(data$tidak_sekolah, data$jarak_smp, method = "pearson")
cor.test(data$tidak_sekolah, data$jarak_mts, method = "pearson")
cor.test(data$tidak_sekolah, data$jarak_smp_sdrjt, method = "pearson")
cor.test(data$tidak_sekolah, data$jarak_sma, method = "pearson")
cor.test(data$tidak_sekolah, data$jarak_smk, method = "pearson")
cor.test(data$tidak_sekolah, data$jarak_ma, method = "pearson")
cor.test(data$tidak_sekolah, data$jarak_sma_sdrjt, method = "pearson")

## Persentase Desa dengan Akses Sekolah yang Mudah (di desa tersebut ada sekolah, atau jika tidak ada sekolah, maka aksesnya mudah dari sekolah terdekat)
cor.test(data$tidak_sekolah, data$persen_akses_sd, method = "pearson")
cor.test(data$tidak_sekolah, data$persen_akses_mi, method = "pearson")
cor.test(data$tidak_sekolah, data$persen_akses_sd_mi, method = "pearson")
cor.test(data$tidak_sekolah, data$persen_akses_smp, method = "pearson")
cor.test(data$tidak_sekolah, data$persen_akses_mts, method = "pearson")
cor.test(data$tidak_sekolah, data$persen_akses_smp_mts, method = "pearson")
cor.test(data$tidak_sekolah, data$persen_akses_sma, method = "pearson")
cor.test(data$tidak_sekolah, data$persen_akses_smk, method = "pearson")
cor.test(data$tidak_sekolah, data$persen_akses_ma, method = "pearson")
cor.test(data$tidak_sekolah, data$persen_akses_sma_sdrjt, method = "pearson")

## Rumah dan Pemukiman
cor.test(data$tidak_sekolah, data$jml_bts, method = "pearson")
cor.test(data$tidak_sekolah, data$persen_perdesaan, method = "pearson")
cor.test(data$tidak_sekolah, data$persen_tani, method = "pearson")
cor.test(data$tidak_sekolah, data$persen_non_listrik, method = "pearson")
cor.test(data$tidak_sekolah, data$persen_non_internet, method = "pearson")
cor.test(data$tidak_sekolah, data$persen_non_tlp, method = "pearson")
cor.test(data$tidak_sekolah, data$jml_klg_kumuh, method = "pearson")
cor.test(data$tidak_sekolah, data$jml_lokasi_kumuh, method = "pearson")
cor.test(data$tidak_sekolah, data$jml_rmh_kumuh, method = "pearson")

## Bencana Alam
cor.test(data$tidak_sekolah, data$longsor, method = "pearson")
cor.test(data$tidak_sekolah, data$banjir, method = "pearson")
cor.test(data$tidak_sekolah, data$banjir_bandang, method = "pearson")
cor.test(data$tidak_sekolah, data$kebakaran_hutan, method = "pearson")


# NON PODES
## Jumlah Sekolah
cor.test(data$tidak_sekolah, data$jml_sd, method = "pearson")
cor.test(data$tidak_sekolah, data$jml_mi, method = "pearson")
cor.test(data$tidak_sekolah, data$jml_sd_sdrjt, method = "pearson")
cor.test(data$tidak_sekolah, data$jml_smp, method = "pearson")
cor.test(data$tidak_sekolah, data$jml_mts, method = "pearson")
cor.test(data$tidak_sekolah, data$jml_smp_sdrjt, method = "pearson")
cor.test(data$tidak_sekolah, data$jml_sma, method = "pearson")
cor.test(data$tidak_sekolah, data$jml_smk, method = "pearson")
cor.test(data$tidak_sekolah, data$jml_ma, method = "pearson")
cor.test(data$tidak_sekolah, data$jml_sma_sdrjt, method = "pearson")

## Jumlah Guru dan KIP
cor.test(data$tidak_sekolah, data$guru_sd, method = "pearson")
cor.test(data$tidak_sekolah, data$guru_mi, method = "pearson")
cor.test(data$tidak_sekolah, data$guru_sd_sdrjt, method = "pearson")
cor.test(data$tidak_sekolah, data$guru_smp, method = "pearson")
cor.test(data$tidak_sekolah, data$guru_mts, method = "pearson")
cor.test(data$tidak_sekolah, data$guru_smp_sdrjt, method = "pearson")
cor.test(data$tidak_sekolah, data$guru_sma, method = "pearson")
cor.test(data$tidak_sekolah, data$guru_smk, method = "pearson")
cor.test(data$tidak_sekolah, data$guru_ma, method = "pearson")
cor.test(data$tidak_sekolah, data$guru_sma_sdrjt, method = "pearson")
cor.test(data$tidak_sekolah, data$kip_sd, method = "pearson")
cor.test(data$tidak_sekolah, data$kip_smp, method = "pearson")
cor.test(data$tidak_sekolah, data$kip_sma, method = "pearson")
cor.test(data$tidak_sekolah, data$kip_smk, method = "pearson")
cor.test(data$tidak_sekolah, data$jml_kip, method = "pearson")

## Jumlah Murid
cor.test(data$tidak_sekolah, data$murid_sd, method = "pearson")
cor.test(data$tidak_sekolah, data$murid_mi, method = "pearson")
cor.test(data$tidak_sekolah, data$murid_sd_sdrjt, method = "pearson")
cor.test(data$tidak_sekolah, data$murid_smp, method = "pearson")
cor.test(data$tidak_sekolah, data$murid_mts, method = "pearson")
cor.test(data$tidak_sekolah, data$murid_smp_sdrjt, method = "pearson")
cor.test(data$tidak_sekolah, data$murid_sma, method = "pearson")
cor.test(data$tidak_sekolah, data$murid_smk, method = "pearson")
cor.test(data$tidak_sekolah, data$murid_ma, method = "pearson")
cor.test(data$tidak_sekolah, data$murid_sma_sdrjt, method = "pearson")

## Rasio Murid Guru dan Dana Pendidikan
cor.test(data$tidak_sekolah, data$rmg_sd, method = "pearson")
cor.test(data$tidak_sekolah, data$rmg_mi, method = "pearson")
cor.test(data$tidak_sekolah, data$rmg_sd_sdrjt, method = "pearson")
cor.test(data$tidak_sekolah, data$rmg_smp, method = "pearson")
cor.test(data$tidak_sekolah, data$rmg_mts, method = "pearson")
cor.test(data$tidak_sekolah, data$rmg_smp_sdrjt, method = "pearson")
cor.test(data$tidak_sekolah, data$rmg_sma, method = "pearson")
cor.test(data$tidak_sekolah, data$rmg_smk, method = "pearson")
cor.test(data$tidak_sekolah, data$rmg_ma, method = "pearson")
cor.test(data$tidak_sekolah, data$rmg_sma_sdrjt, method = "pearson")
cor.test(data$tidak_sekolah, data$dau_pendidikan_6, method = "pearson")
cor.test(data$tidak_sekolah, data$dak_pendidikan_6, method = "pearson")

## Lain-lain
cor.test(data$tidak_sekolah, data$jml_penduduk, method = "pearson")
cor.test(data$tidak_sekolah, data$elevasi, method = "pearson")
cor.test(data$tidak_sekolah, data$ntl, method = "pearson")
cor.test(data$tidak_sekolah, data$pdrb_perkapita, method = "pearson")

```

## Varians Penduga Langsung
```{r}
data$vardir <- (data$rse/100*data$tidak_sekolah)^2
```


# EBLUP
## Model Terbaik
```{r}
fh(
  tidak_sekolah ~ jml_sd_sdrjt + 
    jml_smp_sdrjt +
    dau_pendidikan_6,
  vardir = "vardir",
  combined_data = data.frame(data),
  MSE = T,
  method = "ml") -> res_eblup

emdi::compare(res_eblup)
emdi::compare_plot(res_eblup)
summary(res_eblup)
plot(res_eblup)

res_eblup$MSE # MSE EBLUP
res_m1 <- sqrt(res_eblup$MSE$FH)/res_eblup$ind$FH*100
res_m1
data$rse_m1 <- res_m1
res_eblup$ind

summary(res_eblup$ind$Direct)
summary(res_eblup$ind$FH)

shapiro.test(res_eblup$model$random_effects)
shapiro.test(res_eblup$model$real_residuals)
```

## Dataframe EBLUP
```{r}
data_est <- read_excel("Data Kalimantan Fix 20 Mei.xlsx", sheet="Sheet 1")
data_dirprov <- read_excel("Data Kalimantan Fix 20 Mei.xlsx", sheet="DIrectProv")

data_eblup <- data.frame("prov" = data_est$namaprov,
                         "kabkot" = data$kabkot, 
                         "kode" = data$id_kab,
                         "direct_est" = data$tidak_sekolah,
                         "eblup_est" = res_eblup$ind$FH,
                         "rse_direct" = data$rse,
                         "rse_eblup" = data$rse_m1)

data_eblup <- data_eblup %>%
  mutate(no = row_number())
head(data_eblup)
```

## Grafik EBLUP
```{r}
library(ggplot2)

# line chart
ggplot(data=data_eblup, 
       aes(x=no, group=1)) +
  geom_line(aes(y=rse_direct), color="darkred") +
  geom_line(aes(y=rse_eblup), color="steelblue") +
  labs(x="id",
       y="Nilai RSE")

ggplot(data=data_eblup,
       aes(x=prov,
           y=eblup_est,
           color=prov)) +
  geom_boxplot() +
  geom_point(data=data_dirprov,
             aes(x=prov,
                 y=ATS),
             color="red") +
  labs(x = "Provinsi",
       y = "Estimasi EBLUP") +
  guides(color=guide_legend(title="Provinsi"))
```


```{r}
step(res_eblup) -> res_eblup_step
sqrt(res_eblup_step$MSE$FH)/res_eblup_step$ind$FH*100
```

## Hierarchical Bayes

Model yang ditampilkan merupakan 4 model "terbaik" yang telah dicobakan
```{r}
# Model 1
Beta(
  tidak_sekolah_beta ~ jml_sd_sdrjt +
    pdrb_perkapita +
    persen_non_listrik +
    persen_perdesaan,
  data = data %>%
    mutate(
      tidak_sekolah_beta = tidak_sekolah/100),
  iter.update = 100,
  iter.mcmc = 20000,
  thin = 2,
  burn.in = 2000) -> res_beta


# Model 2
Beta(
  tidak_sekolah_beta ~ murid_smk +
    dau_pendidikan,
  data = data %>%
    mutate(
      tidak_sekolah_beta = tidak_sekolah/100),
  iter.update = 100,
  iter.mcmc = 20000,
  thin = 2,
  burn.in = 2000) -> res_beta_2

# Model 7
Beta(
  tidak_sekolah_beta ~ jml_sd_sdrjt +
    jml_smp_sdrjt + 
    persen_akses_smp_mts +
    persen_akses_sma_sdrjt +
    dau_pendidikan +
    pdrb_perkapita +
    persen_non_listrik +
    persen_tani +
    persen_perdesaan,
  data = data %>%
    mutate(
      tidak_sekolah_beta = tidak_sekolah/100),
  iter.update = 100,
  iter.mcmc = 20000,
  thin = 2,
  burn.in = 2000) -> res_beta_7


# Model 8
Beta(
  tidak_sekolah_beta ~ jml_sd_sdrjt +
    jml_smp_sdrjt + 
    #persen_akses_smp_mts +
    persen_akses_sma_sdrjt +
    dau_pendidikan +
    pdrb_perkapita +
    #persen_non_listrik +
    persen_tani +
    persen_perdesaan,
  data = data %>%
    mutate(
      tidak_sekolah_beta = tidak_sekolah/100),
  iter.update = 100,
  iter.mcmc = 20000,
  thin = 2,
  burn.in = 2000) -> res_beta_8

```

### RDS HB (object)
```{r}
library(readr)
write_rds(res_beta,
          "20240520_res beta.Rds")
res_beta$Est$SD/res_beta$Est$MEAN * 100
# write_r
res_beta$coefficient

# Model 2

write_rds(res_beta_2,
          "res beta 2.Rds")
res_beta_2$Est$SD/res_beta_2$Est$MEAN * 100
res_beta_2$coefficient*100

# Model 7 
write_rds(res_beta_7,
          "res beta 7.Rds")
res_beta_7$Est$SD/res_beta_7$Est$MEAN * 100
res_beta_7$coefficient*100
res_beta_7$Est

datam7 <- data.frame("prov" = data_est$namaprov,
                     "kabkot" = data$kabkot, 
                     "kode" = data$id_kab,
                     "direct_est" = data$tidak_sekolah,
                     "hb_est" = res_beta_7$Est$MEAN * 100,
                     "rse_direct" = data$rse,
                     "rse_hb" = res_beta_7$Est$SD/res_beta_7$Est$MEAN * 100)

datam_eblup <- data.frame("prov" = data_est$namaprov,
                     "kabkot" = data$kabkot, 
                     "kode" = data$id_kab,
                     "direct_est" = data$tidak_sekolah,
                     "eblup_est" = res_eblup$ind$FH,
                     "hb_est" = res_beta_7$Est$MEAN * 100,
                     "rse_direct" = data$rse,
                     "rse_eblup" = sqrt(res_eblup$MSE$FH)/res_eblup$ind$FH*100,
                     "rse_hb" = res_beta_7$Est$SD/res_beta_7$Est$MEAN * 100,
                     "se_direct" = sqrt(res_eblup$MSE$FH),
                     "se_hb" = res_beta_7$Est$SD )
library(writexl)
write_xlsx(datam_eblup, "Data SAE Kelompok 2-2.xlsx")
datam7 <- datam7 %>%
  mutate(id = row_number())
library(dplyr)

datam_eblup <- datam_eblup %>%
  mutate(id = row_number())
library(dplyr)

# Model 8 
write_rds(res_beta_8,
          "res beta 8.Rds")
res_beta_8$Est$SD/res_beta_8$Est$MEAN * 100
res_beta_8$coefficient

```
**Diperoleh Model HB Terbaik Adalah Model 7**

### GRAFIK HB PULAU
```{r}
library(ggplot2)

# reshape
head(datam7)
library(reshape2)
datam7rse <- datam7 %>%
  select(id, rse_direct, rse_hb)
datam7rse <- reshape2::melt(datam7rse, id.var="id")

datam_eblup_rse <- datam_eblup %>%
  select(id, rse_direct, rse_eblup, rse_hb)
datam_eblup_rse <- reshape2::melt(datam_eblup_rse, id.var="id")

summary(datam7$rse_hb)
summary(datam7$rse_direct)
summary(datam7$hb_est)
summary(datam7$direct_est)
cor(datam7$hb_est, datam7$direct_est)
cor(datam_eblup$eblup_est, datam7$direct_est)

datam7est <- datam7 %>%
  select(id, direct_est, hb_est)

datam_eblup_est <- datam_eblup %>%
  select(id, direct_est, eblup_est, hb_est)

datam7est <- reshape2::melt(datam7est, id.var="id")

datam_eblup_est <- reshape2::melt(datam_eblup_est, id.var="id")
  
# line chart
## rse
ggplot(data=datam7rse, 
       aes(x=id, y=value, colour=variable)) +
  geom_point() +
  geom_line() +
  labs(x="id",
       y="Nilai RSE") + 
  guides(color=guide_legend(title="Model"))

ggplot(data=datam_eblup_rse, 
       aes(x=id, y=value, colour=variable)) +
  geom_point() +
  geom_line() +
  labs(x="id",
       y="Nilai RSE") + 
  guides(color=guide_legend(title="Model"))

## estimate
ggplot(data=datam7est, 
       aes(x=id, y=value, colour=variable)) +
  geom_point() +
  geom_line() +
  labs(x="id",
       y="Nilai Penduga") + 
  guides(color=guide_legend(title="Model"))

ggplot(data=datam_eblup_est, 
       aes(x=id, y=value, colour=variable)) +
  geom_point() +
  geom_line() +
  labs(x="id",
       y="Nilai Penduga") + 
  guides(color=guide_legend(title="Model"))
  
# boxplot validasi
ggplot(data=datam7,
       aes(x=prov,
           y=hb_est,
           color=prov)) +
  geom_boxplot() +
  geom_point(data=data_dirprov,
             aes(x=prov,
                 y=ATS),
             color="red") +
  labs(x = "Provinsi",
       y = "Penduga HB Beta") +
  guides(color=guide_legend(title="Provinsi"))

ggplot(data=datam_eblup,
       aes(x=prov,
           y=eblup_est,
           color=prov)) +
  geom_boxplot() +
  geom_point(data=data_dirprov,
             aes(x=prov,
                 y=ATS),
             color="red") +
  labs(x = "Provinsi",
       y = "Penduga EBLUP") +
  guides(color=guide_legend(title="Provinsi"))
```


